---
# handlers file for telegraf-windows


- name: restart telegraf service
  win_service:
    name: telegraf
    state: restarted

- name: stop telegraf service
  win_service:
    name: telegraf
    state: stopped